GestorVisitas.Web/Models/ErrorViewModel.cs
namespace GestorVisitas.Web.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

GestorVisitas.Web/Controllers/FiltroVisitasController.cs
using GestorVisita.Data.Interface;
using Microsoft.AspNetCore.Mvc;

namespace GestorVisitas.Web.Controllers
{
    public class FiltroVisitasController : Controller
    {
        private readonly IFiltroVisita _visitaDao;

        public FiltroVisitasController(IFiltroVisita visitaDao)
        {
            _visitaDao = visitaDao;
        }

        // Acción para mostrar todas las visitas
        public ActionResult FiltroVisita() 
        {
            var FiltroVisitas = _visitaDao.ObtenerTodas();
            return View(FiltroVisitas);
        }

        // Acción para filtrar visitas por fecha
        public ActionResult FiltrarPorFecha(DateTime fecha)
        {
            var visitasFiltradas = _visitaDao.FiltrarPorFecha(fecha);
            return View("Index", visitasFiltradas);
        }

    }
}

GestorVisitas.Web/Controllers/HomeController.cs
using GestorVisitas.Web.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace GestorVisitas.Web.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

GestorVisitas.Web/Controllers/UsuariosController.cs
using GestorVisita.Data.Daos;
using GestorVisita.Data.Entities;
using GestorVisita.Data.Interface;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace GestorVisitas.Web.Controllers
{
    public class UsuariosController : Controller
    {
        private readonly IDaoUsuario daoUsuario;

        public UsuariosController(IDaoUsuario daoUsuario)
        {
            this.daoUsuario = daoUsuario;
        }

        // GET: UsuariosController
        public ActionResult Index()
        {
            var result = daoUsuario.GetUsuarios();
            var data = result.OrderBy(x => x.Id).ToList();
            return View(data);
        }

        // GET: UsuariosController/Details/5
        public ActionResult Details(int id)
        {
            var result = daoUsuario.GetUsuariosById(id);
            return View(result);
        }

        // GET: UsuariosController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: UsuariosController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Usuarios collection)
        {
            try
            {
                daoUsuario.AddUsuario(collection);
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: UsuariosController/Edit/5
        public ActionResult Edit(int id)
        {
            var result = daoUsuario.GetUsuariosById(id);
            return View(result);
        }

        // POST: UsuariosController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, Usuarios collection)
        {
            try
            {
                daoUsuario.UpdateUsuario(collection);
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: UsuariosController/Delete/5
        public ActionResult Delete(int id)
        {
            var result = daoUsuario.GetUsuariosById(id);
            return View(result);
        }

        // POST: UsuariosController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                daoUsuario.DeleteUsuario(id);
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

GestorVisitas.Web/Controllers/VisitaController.cs
using GestorVisita.Data.Entities;
using GestorVisita.Data.Interface;
using Microsoft.AspNetCore.Mvc;

namespace GestorVisitas.Web.Controllers
{
    public class VisitaController : Controller
    {
        private readonly IDaoVisita daoVisita;

        public VisitaController(IDaoVisita daoVisita)
        {
            this.daoVisita = daoVisita;
        }
        // GET: VisitaController
        public ActionResult Index()
        {
            var result = daoVisita.GetVisitas();
            var data = result.OrderBy(x => x.Id).ToList();
            return View(data);
        }

        // GET: VisitaController/Details/5
        public ActionResult Details(int id)
        {
            var result = daoVisita.GetVisitaById(id);
            return View(result);
        }

        // GET: VisitaController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: VisitaController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Visita collection)
        {
            try
            {
                daoVisita.AddVisita(collection);
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: VisitaController/Edit/5
        public ActionResult Edit(int id)
        {
            var result = daoVisita.GetVisitaById(id);
            return View(result);
        }

        // POST: VisitaController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, Visita collection)
        {
            try
            {
                daoVisita.UpdateVisita(collection);
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: VisitaController/Delete/5
        public ActionResult Delete(int id)
        {
            var result = daoVisita.GetVisitaById(id);
            return View(result);
        }

        // POST: VisitaController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                daoVisita.DeleteVisita(id);
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

GestorVisitas.Web/Views/FiltroVisitas/F_Visitas.cshtml
@model IEnumerable<GestorVisita.Data.Entities.FiltroVisitas>


@{
    ViewData["Title"] = "Filtros de Visitas";
    ViewBag.Title = "Visitas";
}


<h2>Filtro de Visitas</h2>

<table class="table">
    <thead>
        <tr>
            <th>Nombre</th>
            <th>Fecha</th>
            <th>Detalles</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var FiltroVisitas in Model)
        {
            <tr>
                <td>@FiltroVisitas.Nombre</td>
                <td>@FiltroVisitas.Fecha.ToString("dd/MM/yyyy")</td>
                <td>@FiltroVisitas.Detalles</td>
            </tr>
        }
    </tbody>
</table>

<form action="@Url.Action("FiltrarPorFecha", "Visitas")" method="get">
    <div class="form-group">
        <label for="fecha">Filtrar por Fecha:</label>
        <input type="date" id="fecha" name="fecha" class="form-control" />
    </div>
    <button type="submit" class="btn btn-primary">Filtrar</button>
</form>

GestorVisitas.Web/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

GestorVisitas.Web/Views/Login/Login.cshtml
@{
    ViewData["Title"] = "Index";
}


<div class="Text container">
    <label>User</label>     <br />
    <input type="text" />    <br />
    <label>Password</label> <br />
    <input type="password" />
   2

</div>

GestorVisitas.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - GestorVisitas.Web</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/GestorVisitas.Web.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">GestorVisitas</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Visita" asp-action="Index">Visitas</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="FiltroVisitas" asp-action="F_Visitas">Filtro Visitas</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - GestorVisitas.Web - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

GestorVisitas.Web/Views/Usuarios/Create.cshtml
@model GestorVisita.Data.Entities.Usuarios

@{
    ViewData["Title"] = "Create";
}

<h1>CREANDO NUEVO USUARIO</h1>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            @* <div class="form-group">
            <label asp-for="Id" class="control-label"></label>
            <input asp-for="Id" class="form-control" />
            <span asp-validation-for="Id" class="text-danger"></span>
            </div> *@
            <div class="form-group">
                <label asp-for="Nombre" class="control-label"></label>
                <input asp-for="Nombre" class="form-control" />
                <span asp-validation-for="Nombre" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input type="email" asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Contraseña" class="control-label"></label>
                <input type="password" asp-for="Contraseña" class="form-control" />
                <span asp-validation-for="Contraseña" class="text-danger"></span>
            </div>
            @* <div class="form-group">
            <label asp-for="Fecha" class="control-label"></label>
            <input asp-for="Fecha" class="form-control" />
            <span asp-validation-for="Fecha" class="text-danger"></span>
            </div> *@
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

GestorVisitas.Web/Views/Usuarios/Delete.cshtml
@model GestorVisita.Data.Entities.Usuarios

@{
    ViewData["Title"] = "Delete";
}

<h1>ELIMINANDO NUEVO USUARIO</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>USUARIO</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Id)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Id)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Nombre)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Email)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Contraseña)
        </dt>
    </dl>

    <form asp-action="Delete">
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

GestorVisitas.Web/Views/Usuarios/Details.cshtml
@model GestorVisita.Data.Entities.Usuarios

@{
    ViewData["Title"] = "Details";
}

<h1>DETALLE DEL USUARIO</h1>

<div>
    <h4>USUARIO</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Id)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Id)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Nombre)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Email)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Contraseña)
        </dt>
    </dl>
</div>
<div>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    <a asp-action="Index">Back to List</a>
</div>

GestorVisitas.Web/Views/Usuarios/Edit.cshtml
@model GestorVisita.Data.Entities.Usuarios

@{
    ViewData["Title"] = "Edit";
}

<h1>EDITANDO USUARIO</h1>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Id" class="control-label"></label>
                <input readonly asp-for="Id" class="form-control" />
                <span asp-validation-for="Id" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Nombre" class="control-label"></label>
                <input asp-for="Nombre" class="form-control" />
                <span asp-validation-for="Nombre" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input type="email" asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Contraseña" class="control-label"></label>
                <input type="password" asp-for="Contraseña" class="form-control" />
                <span asp-validation-for="Contraseña" class="text-danger"></span>
            </div>

            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

GestorVisitas.Web/Views/Usuarios/Index.cshtml
@model IEnumerable<GestorVisita.Data.Entities.Usuarios>

@{
    ViewData["Title"] = "Index";
}

<h1>LISTADO DE Usuarios</h1>

<p>
    <a asp-action="Create">CREAR NUEVO USUARIO</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Id)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Nombre)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Email)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Contraseña)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Id)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Nombre)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Email)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Contraseña)
                </td>
                <td>
                    @Html.ActionLink("Edit", "Edit", new { id = item.Id }) |
                    @Html.ActionLink("Details", "Details", new { id = item.Id }) |
                    @Html.ActionLink("Delete", "Delete", new { id = item.Id })
                </td>
            </tr>
        }
    </tbody>
</table>

GestorVisitas.Web/Views/Visita/Create.cshtml
@model GestorVisita.Data.Entities.Visita

@{
    ViewData["Title"] = "Create";
}

<h1>CREANDO NUEVA VISITA</h1>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            @* <div class="form-group">
                <label asp-for="Id" class="control-label"></label>
                <input asp-for="Id" class="form-control" />
                <span asp-validation-for="Id" class="text-danger"></span>
            </div> *@
            <div class="form-group">
                <label asp-for="NombreVisitante" class="control-label"></label>
                <input asp-for="NombreVisitante" class="form-control" />
                <span asp-validation-for="NombreVisitante" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="MotivoVisita" class="control-label"></label>
                <input asp-for="MotivoVisita" class="form-control" />
                <span asp-validation-for="MotivoVisita" class="text-danger"></span>
            </div>
           
            @* <div class="form-group">
                <label asp-for="Fecha" class="control-label"></label>
                <input asp-for="Fecha" class="form-control" />
                <span asp-validation-for="Fecha" class="text-danger"></span>
            </div> *@
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

GestorVisitas.Web/Views/Visita/Delete.cshtml
@model GestorVisita.Data.Entities.Visita

@{
    ViewData["Title"] = "Delete";
}

<h1>ELIMINANDO NUEVA VISITA</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Visita</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Id)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Id)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.NombreVisitante)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.NombreVisitante)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.MotivoVisita)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.MotivoVisita)
        </dd>
       
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Fecha)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Fecha)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

GestorVisitas.Web/Views/Visita/Details.cshtml
@model GestorVisita.Data.Entities.Visita

@{
    ViewData["Title"] = "Details";
}

<h1>DETALLE DE LA VISITA</h1>

<div>
    <h4>Visita</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Id)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Id)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.NombreVisitante)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.NombreVisitante)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.MotivoVisita)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.MotivoVisita)
        </dd>
      
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Fecha)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Fecha)
        </dd>
    </dl>
</div>
<div>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    <a asp-action="Index">Back to List</a>
</div>

GestorVisitas.Web/Views/Visita/Edit.cshtml
@model GestorVisita.Data.Entities.Visita

@{
    ViewData["Title"] = "Edit";
}

<h1>EDITANDO VISITA</h1>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Id" class="control-label"></label>
                <input readonly asp-for="Id" class="form-control" />
                <span asp-validation-for="Id" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="NombreVisitante" class="control-label"></label>
                <input asp-for="NombreVisitante" class="form-control" />
                <span asp-validation-for="NombreVisitante" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="MotivoVisita" class="control-label"></label>
                <input asp-for="MotivoVisita" class="form-control" />
                <span asp-validation-for="MotivoVisita" class="text-danger"></span>
            </div>
          
            
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

GestorVisitas.Web/Views/Visita/Index.cshtml
@model IEnumerable<GestorVisita.Data.Entities.Visita>

@{
    ViewData["Title"] = "Index";
}

<h1>LISTADO DE VISTAS</h1>

<p>
    <a asp-action="Create">CREAR NUEVA VISITA</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Id)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.NombreVisitante)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.MotivoVisita)
            </th>
          
            <th>
                @Html.DisplayNameFor(model => model.Fecha)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Id)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.NombreVisitante)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.MotivoVisita)
            </td>
           
            <td>
                @Html.DisplayFor(modelItem => item.Fecha)
            </td>
            <td>
                    @Html.ActionLink("Edit", "Edit", new { id = item.Id }) |
                    @Html.ActionLink("Details", "Details", new { id = item.Id }) |
                    @Html.ActionLink("Delete", "Delete", new { id = item.Id })
            </td>
        </tr>
}
    </tbody>
</table>